module.exports = {
	myAutogeneratedSidebar: [
		{
			type: "autogenerated",
			dirName: ".", // '.' means the current docs folder
		},
		// {
		// 	type: "link",
		// 	label: "API", // The link label
		// 	href: "https://shipyard.readme.io", // The external URL
		// },
		// {
		// 	type: "link",
		// 	label: "Changelog", // The link label
		// 	href: "https://shipyard.canny.io/changelog", // The external URL
		// },
	],
};
